[권상현] ADD : Kakao social login and unit test
wecode-bootcamp-korea/26-2nd-Weterest-backend pull request #5
Opened 2021-11-19 08:14 UTC by gshduet

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- Kakao 로그인 api를 통한 카카오 소셜로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 프론트엔드로부터 kakao access_token을 부여받고 해당 토큰을 통해 카카오 서버로부터 해당 토큰의 유저 정보를 받아옴
2.  get_or_create 메소드와 받아온 유저 정보를 토대로
  a. 해당 정보로 이미 가입한 유저라면 사이트 로그인
  b. 가입하지 않은 유저라면 해당 정보들을 사용해 사이트에 회원가입 시킨 뒤 사이트 로그인
3. 로그인이 완료 된 유저들에게 자체 jwt 토큰을 증정.
4. 만약 프론트엔드로부터 받은 토큰이 유효하지 않은 토큰이라면(유효기간 만료 등) "INVALD_TOKEN"메세지와 401번 에러 반환
5. 정확한 토큰이 입력되지 않아 카카오 서버로부터 유저 정보를 입력 받을 수 없는 경우 "KEY_ERROR"메세지와 400번 에러 반환
6. unit test를 구현하고 설정한 에러코드 별로 테스트를 통과함
<img width="1440" alt="스크린샷 2021-11-19 오후 4 26 12" src="https://user-images.githubusercontent.com/39396492/142588520-b742d453-cef2-4f58-9fec-8339f31f7ede.png">
 

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 카카오 로그인 api를 사용해봄으로써 처음으로 외부 api 사용 루틴을 경험해보았습니다.
- 소셜로그인(카카오) 진행 과정에 대해 알게 됐습니다.
- 지금은 프론트엔드로부터 access token을 받아오고 있으나 지금의 기능을 구현하기 전에 처음 카카오로부터 인가코드를 받아오는 과정부터 유저정보를 받아오는 과정까지 백엔드 자체적으로 받아오는 기능을 구현해봄으로써 카카오 소셜로그인 루틴에 대해 자세히 알게 됐습니다.
- unit test를 통해 구현한 기능에 대한 검증 과정을 진행해보았으며 unit test의 중요성을 알게 됐습니다.

<br />

## :: 기타 질문 및 특이 사항
- 해당 없음.

2021-11-19 09:42 UTC, Kang-kyunghun requested changes

2021-11-19 09:42 UTC, Kang-kyunghun commented on users/views.py
> +            user_information   = requests.get("https://kapi.kakao.com/v2/user/me", headers=({"Authorization": f"Bearer {kakao_access_token}"})).json()
requests 모듈을 사용하실 때에는 timeout 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다. timeout 옵션을 추가해 주세요.
```suggestion
            user_information   = requests.get("https://kapi.kakao.com/v2/user/me", headers=({"Authorization": f"Bearer {kakao_access_token}"}), timeout=5).json()
```

2021-11-19 09:42 UTC, Kang-kyunghun commented on users/views.py
> +
카카오로부터 카카오의 고유번호를 무조건 받아야 합니다. 이것은 카카오 계정의 고유 번호이고 이 번호를 통해 우리 db의 유저 데이터를 구분해야하기 때문입니다.

2021-11-19 09:42 UTC, Kang-kyunghun commented on users/views.py
> +            )
get_or_create을 사용 할 때는 확실히 데이터를 특정 지을 수 있는 값만 사용해야 합니다.(ex pk) 카카오 로그인 경우에는 kakao_id가 이에 해당합니다. create 할 때 추가 되어야 하는 부수적인 데이터는 default 옵션을 사용해 주세요. defualt 옵션은 create 되는 경우에만 디비에 적용되는 값입니다.
```suggestion
            user, create = User.objects.get_or_create(
                kakao_id = kakao_id,
                default = {
                    email             = email,
                    nickname          = nickname,
                    profile_image_url = profile_image_url,
                    login_platform    = login_platform
                }
            )
```

2021-11-19 09:46 UTC, gshduet commented on users/views.py
> +            user_information   = requests.get("https://kapi.kakao.com/v2/user/me", headers=({"Authorization": f"Bearer {kakao_access_token}"})).json()
기능 구현에 급급해 해당 모듈에 대한 제대로 된 학습이 되지 않았던 것 같습니다. 따끔한 피드백 감사드립니다!

2021-11-19 09:46 UTC, gshduet commented on users/views.py
> +
db 설계 과정에서 놓쳤던 부분인 것 같습니다. db 업데이트 후 해당 피드백 반영하도록 하겠습니다.

2021-11-19 09:46 UTC, gshduet commented on users/views.py
> +            )
해당 피드백 역시 db에 kakao_id 필드 추가 후 반영하도록 하겠습니다!

2021-11-22 04:38 UTC, gshduet commented
피드백 반영 및 로그인 데코레이터 기능 추가하여 다시 pr 올렸습니다..!

2021-11-22 05:43 UTC, gshduet commented
수정된 models 및 views 반영한 tests.py 업데이트 후 pr 완료했습니다.

2021-11-22 14:55 UTC, lordmyshepherd commented
LGTM 👍

2021-11-22 14:55 UTC, merged